### ISSUE TITLE
Selection of conformance classes

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gpkg10#28]
Fixes to the interface are required as follows:

- [x] The tests says that the metadata conformance classes has been implemented and the code exists, but it s not available to the user when starting the test. 
   - See description of the file: http://opengeospatial.github.io/ets-gpkg10/
   - Code is: https://github.com/opengeospatial/ets-gpkg10/tree/master/src/main/java/org/opengis/cite/gpkg10/metadata
   - But when I start the test I don't see the the 'metadata' conformance class
- [x] Make possible to select tiles and metadata at the same time
- [x] The core should be selected by default. Cannot be unselected.  It is the minimum conformance class to get certified.

**Comment by keshavnangare** [comment]
@bermud 

Can you please elaborate on the first point, I am not getting what exactly need to do in the first case.

I have updated the test according to the second and third point.

Thanks.

**Comment by bermud** [comment]
I updated the description with more information about first point.

**Comment by rjmartell** [comment]
The testng.xml file only defines two conformance classes: **Core** and **Tiles**. A test (set) that includes the tests in the metadata package needs to be added.

**Comment by keshavnangare** [comment]
We have updated the test with the metadata conformance class. Now metadata conformance class(CC) is visible to user in web-form.

![image](https://cloud.githubusercontent.com/assets/14732650/21893591/98644370-d901-11e6-9113-f1ebcc096dae.png)

Now the test will execute core CC by default if no other CC's are selected and we can execute all the CC at the same time.

Fixed with this commit: 65c108aed761d0e58a76669cf1512b25a987f2b9
