### ISSUE TITLE
Add conformance class configuration into the gpkg10 test.

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-gpkg10#33]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:
https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by dstenger** [comment]
@jyutzler Can you please name the basic conformance classes? Are these equal to ets-gpkg12 test suite?

**Comment by jyutzler** [comment]
I did not develop the 1.0/1.1 conformance tests, but what I remember is that they only covered the core and tiles portions of the standard. Does that answer the question?

**Comment by dstenger** [comment]
Thank you for the answer. So, you are not the test lead of this suite?

**Comment by jyutzler** [comment]
This 1.0 suite was developed without my direct input (that was @LLambertRGi and I do not know if he is available anymore). I took over the effort last year when we realized that the lack of a complete suite was a major problem. Since it was specifically designed in conjunction with GeoPackage 1.2, we gave it a new repository name but it contains tests for 1.0/1.1 as well.

**Comment by dstenger** [comment]
According to [1] just "Core" is the minimum requirement to be a valid GeoPackage file.

Commit: https://github.com/opengeospatial/ets-gpkg10/commit/edfc64c59123ac01b170818d44784ce1ad0f91d0

[1] https://portal.opengeospatial.org/files/?artifact_id=63378&version=1
